spring:
  application:
    name: ai-code
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: deepseek-v3.2
        api-key: https://bailian.console.aliyun.com/cn-beijing/tab=home?tab=app#/api-key
      streaming-chat-model:
        model-name: deepseek-v3.2
        api-key: https://bailian.console.aliyun.com/cn-beijing/tab=home?tab=app#/api-key
      embedding-model:
        model-name: text-embedding-v1
        api-key: https://bailian.console.aliyun.com/cn-beijing/tab=home?tab=app#/api-key
bigmodel:
  api-key: https://bigmodel.cn/usercenter/proj-mgmt/apikeys
