spring:
  application:
    name: ai-code
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: deepseek-v3.2
        api-key: sk-094322dd7ffb4185a1fd25806de73c91
#      streaming-chat-model:
#        model-name: deepseek-v3.2
#        api-key: sk-094322dd7ffb4185a1fd25806de73c91
#      embedding-model:
#        model-name: text-embedding-v4
#        api-key: sk-094322dd7ffb4185a1fd25806de73c91
#bigmodel:
#  api-key: sk-094322dd7ffb4185a1fd25806de73c91
